# Generated by Django 3.2.20 on 2024-11-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('isStarter', models.BooleanField()),
                ('game_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=255)),
                ('minutes', models.IntegerField()),
                ('points', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('offensiveRebounds', models.IntegerField()),
                ('defensiveRebounds', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('turnovers', models.IntegerField()),
                ('defensiveFouls', models.IntegerField()),
                ('offensiveFouls', models.IntegerField()),
                ('freeThrowsMade', models.IntegerField()),
                ('freeThrowsAttempted', models.IntegerField()),
                ('twoPointersMade', models.IntegerField()),
                ('twoPointersAttempted', models.IntegerField()),
                ('threePointersMade', models.IntegerField()),
                ('threePointersAttempted', models.IntegerField()),
                ('poster', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Shots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.IntegerField()),
                ('game_id', models.IntegerField()),
                ('isMake', models.BooleanField()),
                ('locationX', models.DecimalField(decimal_places=1, max_digits=10)),
                ('locationY', models.DecimalField(decimal_places=1, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
