# Generated by Django 3.2.20 on 2024-11-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_playerlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerList',
            new_name='AllPlayers',
        ),
    ]
