# Generated by Django 3.2.20 on 2024-11-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_team'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
    ]
