# Generated by Django 3.2.20 on 2024-11-26 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_team_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allplayers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='shots',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='allplayers',
            table='app.all_players',
        ),
        migrations.AlterModelTable(
            name='player',
            table='app.app_player',
        ),
        migrations.AlterModelTable(
            name='shots',
            table='app.app_shots',
        ),
        migrations.AlterModelTable(
            name='team',
            table='app.teams',
        ),
    ]
