# Generated by Django 3.2.20 on 2024-11-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20241126_0206'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allplayers',
            table='all_players',
        ),
        migrations.AlterModelTable(
            name='player',
            table='app_player',
        ),
        migrations.AlterModelTable(
            name='shots',
            table='app_shots',
        ),
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
    ]
